language: java

install:
  - export VERSION=6.3-rc-4
  - wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip
  - mkdir /tmp/gradle
  - unzip -d /tmp/gradle gradle-${VERSION}-bin.zip
  - export PATH=/tmp/gradle/gradle-${VERSION}/bin:$PATH
  - gradle -v

dist: xenial

os:
  - linux
  - osx

jdk:
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8

jobs:
  allow_failures:
    - os: osx
      jdk: openjdk8
    - jdk: openjdk15
